name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        # This also runs javadoc:javadoc to detect any issues with the Javadoc
        run: mvn --batch-mode --update-snapshots verify javadoc:javadoc
